Messages:
  PotionNotFound: '&c&lError: Potion not found!'
  PlayerNotFound: '&c&lError: a player with the name ''{name}'' could not be found!'
  NotEnoughArgs: '&c&lError: Syntax error. Use the command like this {command}'
  NoPermission: '&c&lError: You do not have permission to {feature}'
  TargetNotFound: '&c&lError: Target could not be found please use a valid faction tag or player name!'
  NoFaction: '&c&lError: The faction you attempted to ban is Wilderness!'
FactionBan:
  Disband: true
AntiDupe:
  InventoryCache:
    # This task will prepare inventories to be scanned on the other thread
    SyncTaskInterval: 10
    # The thread dedicated to scanning will stop checking for new inventories if none are ready for X milliseconds
    AsyncTaskSleep: 15
  PunishmentCommands:
    - '/ipban {player} Suspicious items detected.'
Discord:
  Token: ''
  # All status messages support PlaceholderAPI
  Status:
    UpdateInterval: 30
    # Activity types: DEFAULT (Playing), WATCHING, LISTENING
    Whitelisted:
      Activity: 'WATCHING'
      Message: '%server_name% undergo maintenance'
    Open:
      Activity: 'DEFAULT'
      Message: '%server_name% with %online_players% players'
  Bot:
    # Bot responses support PlaceholderAPI
    -online: '%online_players% Players online.'
    -tps: 'Current TPS: %server_tps%'
    command: 'response'
CustomCommands:
  # Responses support PlaceholderAPI
  vote:
    - '&b&l Link 1'
    - '&8&l Link 2'
    - '&b&l Etc'
CustomPotions:
  # Potion names and lore support PlaceholderAPI
  SpawnPotion:
    Name: '&b&lSpawn Potion'
    Lore:
      - '&bPlayers hit by this potion are instantly sent to spawn'
      - '&8Manufactured for %player_name%'
    Type: 'WATER'
    Level: 1
    Extended: false
    Stackable: false
    Commands:
      - 'spawn {affected}'
    # 1.9 or Later
    Color:
      Blue: 50
      Green: 50
      Red: 50
  # Use {affected} for players who are hit by the potion.
CustomMobs:
  custom1:
    Chance: 10
    Entity: ZOMBIE
    Name: '&8&lWicked Zombie'
    Effects:
      - 'Strength'
      - 'Speed'
    Weapon:
      Material: Iron_Sword
      Enchantments:
        - 'Sharpness, 1'
    Drops:
      item1:
        Chance: 100
        Name: 'Diamond'
        Material: DIAMOND
        Amount: 1
        Enchantments:
        Lore:
Perks:
  Quick Reload:
    Effect: false
    ### This permission is for checking if the player has access to the perk not if it is enabled! ###
    Permission: Core.QuickReload
  Rebreather:
    Effect: false
    Permission: Core.Rebreather
  Enchanced Vision:
    Effect: false
    Permission: Core.EnchancedVision
